### ISSUE TITLE
problem the connection with surveyjs-node

### ISSUE THREAD

**Issue by fradesigner** [surveyjs/surveyjs-nodejs#12]
Hi,
i have a problem the connection with surveyjs-node - create?accessKey=undefined&name=NewSurvey1623920289986 net::ERR_EMPTY_RESPONSE -
I can't connect the postgres database.
Could any of you help me?
Thank you all for your cooperation
<img width="817" alt="Schermata 2021-06-17 alle 12 08 42" src="https://user-images.githubusercontent.com/3780435/122376825-ca247c00-cf64-11eb-94bd-27c066200ac1.png">

**Comment by tsv2013** [comment]
This repo is just a demo how to integrate SurveyJS products with NodeJS backend. Probably you need to check whether your postgresql server is available, your postgresql login/pass. After that you need to debug server side NodeJS code to find the cause of the error.

**Comment by fradesigner** [comment]
I am looking for a component that gives me the possibility to import a survey via a json.
Once the survey has been created or imported, the user simply has to fill in the survey.
I would like to understand if your surveyjs-node could do what I would like to show (including survey results).

**Comment by tsv2013** [comment]
This repo demonstrates how to keep a list of editable survey JSON definitions, run them and show results. It stores survey JSON and results in the session storage. In the real world application you need to add some other functionality like DB storage, security and so on. This functionality is not related to SurveyJS core and thus not implemented here.
