### ISSUE TITLE
The JSON schema in the code doesn't get updated and is not saved when you make changes on the editor.

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs-nodejs#17]
[The issue](https://surveyjs.answerdesk.io/internal/ticket/details/T18032) was reported in SurveyJS technical forum.

**Comment by tsv2013** [comment]
I've checked the the https://surveyjs-nodejs.azurewebsites.net/ site and the https://github.com/surveyjs/surveyjs-nodejs repository. Everything works ok for me according the instructions. Survey and result JSONs are stored in the in-memory session DB. One need to implement own DB adapder to a real DBMS like PostgreSQL, MySQL, Microsoft SQL Server and so on
