### ISSUE TITLE
Bootstrap version

### ISSUE THREAD

**Issue by guilhermesad** [surveyjs/surveyjs-nodejs#2]
Hi there! Thanks for this awesome repo.

Is there a way I can use the Bootstrap version of SurveyJS for the whole application? For example, for `survey.js` I've added the line `Survey.Survey.cssType = "bootstrap";` like they say in the [docs](https://surveyjs.io/Documentation/Library/), but that didn't seem to make any effect.

**Comment by tsv2013** [comment]
It lloks like you need to add a corresponding stylesheet 
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
```
to the
`https://github.com/surveyjs/surveyjs-nodejs/blob/master/public/survey.html`
file
