### ISSUE TITLE
How to retrieve and save survey result in mysql.

### ISSUE THREAD

**Issue by m-saifuddin** [surveyjs/surveyjs-nodejs#5]
Dear Team,

I am following the current example (surveyjs-nodejs) I am able to connect and saved survey data into Database (MySQL) tables but when I try to run the survey using the run button against survey from the main page its doesn't load the form and showing me the message on page "There is no visible page or question in the survey." 

URL: redirect me to below after click run
http://localhost:3000/survey.html?id=2

```
var model = new Survey.Model({ surveyId: surveyId, surveyPostId: surveyId });
model.css = css;
  window.survey = model;
  model.render("surveyElement");

```
Thanks in Advance.

**Comment by tsv2013** [comment]
I've answered here - https://surveyjs.answerdesk.io/ticket/details/T822

**Comment by miranaitamara** [comment]
` throw err; // Rethrow non-MySQL errors
      ^
ReferenceError: logger is not defined` 
@m-saifuddin How I can fix it ??
