### ISSUE TITLE
Docker build problem

### ISSUE THREAD

**Issue by larrybg** [surveyjs/surveyjs-nodejs#7]
"Build postgresql-db docker container via docker build -t postgresql-db . command in the docker/postgresql-db folder" - doesn't work. When running with "-t" docker reports error "docker build" requires exactly 1 argument.
I have removed that "-t" and can run this command from "docker" folder... not from docker/postgresql-db. 
And still unable to build docker container.

**Comment by larrybg** [comment]
UPDATE: after running only "docker build postgresql-db", docker built something....but a "docker ps -a" cannot find any containers. This is definitely broken

**Comment by dmitrykurmanov** [comment]
Hello, we've tried to start the container via the instrucrions in the README and it starts ok. May be you forgot about the dot in this command: `docker build -t postgresql-db .` ?

**Comment by tsv2013** [comment]
I've removed docker code
