### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by ReemAlmuhimeed** [surveyjs/surveyjs-nodejs#8]
I'm not sure what causing this I tried to track it but I couldn't find anything. is there a certain package I need  to update? or how I can handle it

<img width="773" alt="screen shot 1440-04-27 at 11 57 24 am" src="https://user-images.githubusercontent.com/34995865/50629783-13c4ac00-0f4f-11e9-86e9-a309cade6e3d.png">

**Comment by dmitrykurmanov** [comment]
duplicate for https://surveyjs.answerdesk.io/ticket/details/T1455
